#cloud-config
package_update: true
package_upgrade: true
packages: [curl, jq, tar, apt-transport-https]
write_files:
  - path: /opt/runner/env.sh
    permissions: "0644"
    owner: root:root
    content: |
      RUNNER_KIND="{0}"
      AZP_URL="{1}"
      AZP_POOL="{2}"
      AZP_AGENT_NAME="{3}"
      AZP_WORK="{4}"
      GH_OWNER="{5}"
      GH_REPO="{6}"
      GH_LABELS="{7}"
      GH_AGENT_NAME="{8}"
      GH_WORK="{9}"
      AZP_PAT="{10}"
      GH_PAT="{11}"
runcmd:
  - [ bash, -lc, "useradd -m {12} -s /bin/bash || true" ]
  - |
    bash -lc "mkdir -p /home/{12}/.ssh && \
      echo '{13}' >> /home/{12}/.ssh/authorized_keys && \
      chown -R {12}:{12} /home/{12}/.ssh && \
      chmod 600 /home/{12}/.ssh/authorized_keys"
  - |
    bash -lc "if [ \"$RUNNER_KIND\" = \"azdo\" ]; then
      AGENT_DIR=\"$AZP_WORK\"; if [ -z \"$AGENT_DIR\" ]; then AGENT_DIR=/opt/azdo-agent; fi; mkdir -p \"$AGENT_DIR\"; cd \"$AGENT_DIR\";
      curl -LsS https://vstsagentpackage.azureedge.net/agent/3.240.1/vsts-agent-linux-x64-3.240.1.tar.gz -o agent.tar.gz;
      tar zxvf agent.tar.gz;
      ./bin/installdependencies.sh;
      A_NAME=\"$AZP_AGENT_NAME\"; if [ -z \"$A_NAME\" ]; then A_NAME=build-{14}; fi;
      WORKF=\"$AZP_WORK\"; if [ -z \"$WORKF\" ]; then WORKF=_work; fi;
      ./config.sh --unattended --url \"$AZP_URL\" --auth pat --token \"$AZP_PAT\" --pool \"$AZP_POOL\" --agent \"$A_NAME\" --work \"$WORKF\" --replace;
      ./svc.sh install; ./svc.sh start;
    else
      RUNNER_DIR=\"$GH_WORK\"; if [ -z \"$RUNNER_DIR\" ]; then RUNNER_DIR=/opt/github-runner; fi; mkdir -p \"$RUNNER_DIR\"; cd \"$RUNNER_DIR\";
      LATEST=$(curl -s https://api.github.com/repos/actions/runner/releases/latest | jq -r .tag_name);
      LATEST_NO_V=$(echo \"$LATEST\" | sed 's/^v//');
      curl -Lo actions-runner-linux-x64-$LATEST_NO_V.tar.gz https://github.com/actions/runner/releases/download/$LATEST/actions-runner-linux-x64-${LATEST_NO_V}.tar.gz;
      tar xzf actions-runner-linux-x64-$LATEST_NO_V.tar.gz;
      token=$(curl -s -X POST -H \"Authorization: token $GH_PAT\" -H \"Accept: application/vnd.github+json\" https://api.github.com/repos/$GH_OWNER/$GH_REPO/actions/runners/registration-token | jq -r .token);
      LABELS=\"$GH_LABELS\"; if [ -z \"$LABELS\" ]; then LABELS=self-hosted,linux,x64; fi;
      G_NAME=\"$GH_AGENT_NAME\"; if [ -z \"$G_NAME\" ]; then G_NAME=build-{14}; fi;
      WORKG=\"$GH_WORK\"; if [ -z \"$WORKG\" ]; then WORKG=_work; fi;
      ./config.sh --unattended --url https://github.com/$GH_OWNER/$GH_REPO --token \"$token\" --labels \"$LABELS\" --name \"$G_NAME\" --work \"$WORKG\" --replace;
      ./svc.sh install; ./svc.sh start;
    fi"